// <auto-generated />
namespace CourseDotNet.Class2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class crear_tabla_producto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crear_tabla_producto));
        
        string IMigrationMetadata.Id
        {
            get { return "202010032140485_crear_tabla_producto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
